package auth

import (
	"errors"
	"fmt"
	"os"
	"os/exec"
	"strings"
)

// OTP source priority constants
const (
	OTPSourceFlag     = "flag"
	OTPSourceCommand  = "command"
	OTPSourceKeychain = "keychain"
	OTPSourceEnv      = "env"
	OTPSourcePrompt   = "prompt"
)

// Environment variable names for OTP configuration
const (
	EnvOTP        = "CERN_SSO_OTP"
	EnvOTPCommand = "CERN_SSO_OTP_COMMAND"
	// EnvOTPKeychain is defined in keychain.go
)

const (
	defaultMaxOTPAttempts           = 3
	disableRetryOTPAttempts         = 1
	autoGeneratedTOTPMaxOTPAttempts = 2
)

// OTPProvider handles OTP code retrieval from various sources.
// It checks sources in priority order: flag > command > keychain > env > prompt.
type OTPProvider struct {
	OTP             string // Direct OTP value (from --otp flag or CERN_SSO_OTP)
	OTPCommand      string // Command to execute (from --otp-command flag or CERN_SSO_OTP_COMMAND)
	OTPKeychainName string // macOS Keychain service name for OTP secret (from --otp-keychain or CERN_SSO_OTP_KEYCHAIN)
	MaxRetries      int    // Maximum OTP attempts (default: 3, 0 disables retries)
	DisableRetries  bool   // True when retries were explicitly disabled via CLI configuration
}

type otpCandidate struct {
	enabled bool
	source  string
	load    func() (string, error)
	wrapErr func(error) error
}

// GetOTP retrieves an OTP code using the configured sources.
// It tries sources in priority order:
//  1. Direct OTP value (p.OTP)
//  2. OTP command (p.OTPCommand)
//  3. macOS Keychain TOTP (p.OTPKeychainName or CERN_SSO_OTP_KEYCHAIN)
//  4. CERN_SSO_OTP environment variable
//  5. CERN_SSO_OTP_COMMAND environment variable
//  6. Interactive prompt (fallback)
//
// Returns the OTP code and the source it was retrieved from.
func (p *OTPProvider) GetOTP(username string) (string, string, error) {
	for _, candidate := range p.otpCandidates(username) {
		if !candidate.enabled {
			continue
		}

		otp, err := candidate.load()
		if err != nil {
			return "", "", candidate.wrapErr(err)
		}
		return otp, candidate.source, nil
	}

	// Priority 6: Interactive prompt
	otp, err := promptForOTPInteractive(username)
	if err != nil {
		return "", "", err
	}
	return otp, OTPSourcePrompt, nil
}

func (p *OTPProvider) otpCandidates(username string) []otpCandidate {
	envKeychain := os.Getenv(EnvOTPKeychain)
	envOTP := os.Getenv(EnvOTP)
	envCmd := os.Getenv(EnvOTPCommand)

	return []otpCandidate{
		{
			enabled: p.OTP != "",
			source:  OTPSourceFlag,
			load: func() (string, error) {
				return validateOTP(p.OTP)
			},
			wrapErr: func(err error) error {
				return fmt.Errorf("invalid OTP from flag: %w", err)
			},
		},
		{
			enabled: p.OTPCommand != "",
			source:  OTPSourceCommand,
			load: func() (string, error) {
				return executeOTPCommand(p.OTPCommand)
			},
			wrapErr: func(err error) error {
				return fmt.Errorf("OTP command failed: %w", err)
			},
		},
		{
			enabled: p.OTPKeychainName != "",
			source:  OTPSourceKeychain,
			load: func() (string, error) {
				return GenerateKeychainOTP(username, p.OTPKeychainName)
			},
			wrapErr: func(err error) error {
				return fmt.Errorf("keychain OTP failed: %w", err)
			},
		},
		{
			enabled: envKeychain != "",
			source:  OTPSourceKeychain,
			load: func() (string, error) {
				return GenerateKeychainOTP(username, envKeychain)
			},
			wrapErr: func(err error) error {
				return fmt.Errorf("keychain OTP from %s failed: %w", EnvOTPKeychain, err)
			},
		},
		{
			enabled: envOTP != "",
			source:  OTPSourceEnv,
			load: func() (string, error) {
				return validateOTP(envOTP)
			},
			wrapErr: func(err error) error {
				return fmt.Errorf("invalid OTP from %s: %w", EnvOTP, err)
			},
		},
		{
			enabled: envCmd != "",
			source:  OTPSourceEnv,
			load: func() (string, error) {
				return executeOTPCommand(envCmd)
			},
			wrapErr: func(err error) error {
				return fmt.Errorf("OTP command from %s failed: %w", EnvOTPCommand, err)
			},
		},
	}
}

// executeOTPCommand runs a shell command and returns its output as an OTP.
func executeOTPCommand(command string) (string, error) {
	// Use shell to execute the command (supports pipes, etc.)
	// Command is user-configured via CERN_SSO_OTP_COMMAND environment variable
	cmd := exec.Command("sh", "-c", command) // #nosec G702,G204
	output, err := cmd.Output()
	if err != nil {
		var exitErr *exec.ExitError
		if errors.As(err, &exitErr) {
			return "", fmt.Errorf("command exited with status %d: %s", exitErr.ExitCode(), string(exitErr.Stderr))
		}
		return "", err
	}

	otp := strings.TrimSpace(string(output))
	return validateOTP(otp)
}

// validateOTP validates that the OTP is a 6-digit code.
func validateOTP(otp string) (string, error) {
	otp = strings.TrimSpace(otp)
	if len(otp) != 6 {
		return "", fmt.Errorf("OTP must be 6 digits, got %d characters", len(otp))
	}
	for _, c := range otp {
		if c < '0' || c > '9' {
			return "", fmt.Errorf("OTP must contain only digits")
		}
	}
	return otp, nil
}

// promptForOTPInteractive prompts the user interactively for an OTP code.
func promptForOTPInteractive(username string) (string, error) {
	if username != "" {
		fmt.Printf("Enter your 6-digit OTP code for %s: ", username)
	} else {
		fmt.Print("Enter your 6-digit OTP code: ")
	}
	var code string
	_, err := fmt.Scanln(&code)
	if err != nil {
		return "", fmt.Errorf("failed to read input: %w", err)
	}
	return validateOTP(code)
}

// GetMaxRetries returns the configured maximum OTP submission attempts.
// The default is 3 total attempts. A configured value of 0 disables retries,
// which results in a single OTP submission.
func (p *OTPProvider) GetMaxRetries() int {
	if p.DisableRetries {
		return disableRetryOTPAttempts
	}
	if p.MaxRetries <= 0 {
		return defaultMaxOTPAttempts
	}
	return p.MaxRetries
}

func isAutoGeneratedTOTPSource(source string) bool {
	return source == OTPSourceCommand || source == OTPSourceKeychain ||
		(source == OTPSourceEnv && os.Getenv(EnvOTPCommand) != "")
}

func maxOTPAttemptsForSource(source string, configured int) int {
	if isAutoGeneratedTOTPSource(source) && configured > autoGeneratedTOTPMaxOTPAttempts {
		return autoGeneratedTOTPMaxOTPAttempts
	}
	return configured
}

// RefreshOTP gets a fresh OTP for retry attempts.
// For auto-generated TOTP sources, the caller waits for the next TOTP window
// before calling RefreshOTP.
// For interactive sources, it re-prompts the user.
// For static flag sources, it returns an error (cannot refresh).
func (p *OTPProvider) RefreshOTP(username string, source string, attempt, maxRetries int) (string, error) {
	switch source {
	case OTPSourceFlag:
		// Static flag value cannot be refreshed
		return "", fmt.Errorf("cannot refresh static OTP value from --otp flag")

	case OTPSourceCommand:
		// Re-execute the command (already waited in caller)
		return executeOTPCommand(p.OTPCommand)

	case OTPSourceKeychain:
		// Re-generate from keychain (TOTP will produce a fresh code)
		service := p.OTPKeychainName
		if service == "" {
			service = os.Getenv(EnvOTPKeychain)
		}
		return GenerateKeychainOTP(username, service)

	case OTPSourceEnv:
		// Check if it's a command from env or static value
		if envCmd := os.Getenv(EnvOTPCommand); envCmd != "" {
			return executeOTPCommand(envCmd)
		}
		// Static env value cannot be refreshed
		return "", fmt.Errorf("cannot refresh static OTP value from %s", EnvOTP)

	case OTPSourcePrompt:
		// Re-prompt the user
		fmt.Printf("Invalid OTP. Try again (%d/%d): ", attempt, maxRetries)
		var code string
		_, err := fmt.Scanln(&code)
		if err != nil {
			return "", fmt.Errorf("failed to read input: %w", err)
		}
		return validateOTP(code)

	default:
		return "", fmt.Errorf("unknown OTP source: %s", source)
	}
}

// IsRefreshable returns true if the OTP source supports refresh/retry.
func IsRefreshable(source string) bool {
	return source == OTPSourceCommand || source == OTPSourcePrompt ||
		source == OTPSourceKeychain ||
		(source == OTPSourceEnv && os.Getenv(EnvOTPCommand) != "")
}
