name: Release

on:
  release:
    types: [created]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'
          cache: true

      - name: Build all platforms
        run: make build-all VERSION=${{ github.event.release.tag_name }}

      - name: Upload binaries to release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
