name: release-please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          release-type: go
          package-name: cern-sso-cli
          changelog-path: CHANGELOG.md
          include-v-in-tag: true
          labels: release,automated
          bump-minor-pre-major: true
